version: "3.8"

services:
  shell:
    build: ../frontend/shell
    ports:
      - "3000:3000"
    depends_on:
      - dashboard
      - tasks
      - auth

  dashboard:
    build: ../frontend/dashboard
    ports:
      - "3001:3001"

  tasks:
    build: ../frontend/tasks
    ports:
      - "3002:3002"

  auth:
    build: ../frontend/auth
    ports:
      - "3003:3003"

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ../backend/user-service
    container_name: user_service
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/users

  task-service:
    build: ../backend/task-service
    container_name: task_service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasks

  auth-service:
    build: ../backend/auth-service
    container_name: auth_service
    ports:
      - "4002:4002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=mysecretkey

volumes:
  mongo_data:
